package com.travelport.core.service;

import com.adobe.aemfd.docmanager.Document;
import com.adobe.aemds.guide.model.FormSubmitInfo;
import com.adobe.aemds.guide.service.FormSubmitActionService;
import com.adobe.fd.output.api.AcrobatVersion;
import com.adobe.fd.output.api.OutputService;
import com.adobe.fd.output.api.PDFOutputOptions;
import com.adobe.forms.common.service.FileAttachmentWrapper;
import com.day.cq.dam.api.Asset;
import com.day.cq.dam.api.AssetManager;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.commons.lang3.StringUtils;
import org.apache.sling.api.resource.Resource;
import org.apache.sling.api.resource.ResourceResolver;
import org.apache.sling.api.resource.ResourceUtil;
import org.apache.sling.api.resource.ValueMap;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.UUID;

@Component(
    service = FormSubmitActionService.class,
    immediate = true
)
public class CustomSubmitService implements FormSubmitActionService {

    private static final Logger LOG = LoggerFactory.getLogger(CustomSubmitService.class);
    private static final String SERVICE_NAME = "Custom Submit Action";

    private static final String DAM_DOR_FOLDER = "/content/dam/formsanddocuments/dor";

    // JCR property names from Form Model -> Document of Record Template Configuration
    private static final String DOR_TYPE_PROPERTY = "dorType";
    private static final String DOR_TEMPLATE_REF_PROPERTY = "dorTemplateRef";
    private static final String DOR_TYPE_SELECT = "select";

    @Reference
    private OutputService outputService;

    @Override
    public String getServiceName() {
        return SERVICE_NAME;
    }

    @Override
    public Map<String, Object> submit(FormSubmitInfo formSubmitInfo) {
        Map<String, Object> result = new HashMap<>();

        try {
            if (formSubmitInfo == null) {
                setResponseStatus(result, false, "FormSubmitInfo is null");
                return result;
            }

            String jsonData = formSubmitInfo.getData();
            Resource containerResource = formSubmitInfo.getFormContainerResource();
            ResourceResolver resolver = containerResource != null ? containerResource.getResourceResolver() : null;

            LOG.info("Custom Submit Action triggered. Submitted Data: {}", jsonData);

            byte[] pdfBytes = null;

            // 1. Check if DoR PDF was generated by Adaptive Form Engine
            FileAttachmentWrapper dorWrapper = formSubmitInfo.getDocumentOfRecord();
            if (dorWrapper != null) {
                pdfBytes = dorWrapper.getValue();
                LOG.info("Retrieved DoR PDF directly from FormSubmitInfo! Size: {} bytes", pdfBytes != null ? pdfBytes.length : 0);
            }

            // 2. Fallback: Generate DoR PDF programmatically via OutputService using XDP Template
            //    Only if dorType = "select" and dorTemplateRef is configured in Form Properties
            if ((pdfBytes == null || pdfBytes.length == 0) && resolver != null && containerResource != null) {
                String xdpTemplatePath = getDorTemplatePath(containerResource);

                if (StringUtils.isNotBlank(xdpTemplatePath)) {
                    LOG.info("dorType is 'select' and dorTemplateRef is configured. Generating DoR PDF using XDP template: {}", xdpTemplatePath);
                    pdfBytes = generateDoRPdfFromXdp(resolver, jsonData, xdpTemplatePath);
                } else {
                    LOG.info("DoR Template is not configured in Form Properties. Skipping DoR PDF generation.");
                }
            }

            String damPdfPath = null;
            if (pdfBytes != null && pdfBytes.length > 0) {
                LOG.info("Successfully obtained DoR PDF bytes! Size: {} bytes", pdfBytes.length);

                // 3. Save the generated DoR PDF to DAM
                if (resolver != null) {
                    damPdfPath = savePdfToDam(resolver, pdfBytes);
                }
            } else {
                LOG.warn("DoR PDF generation returned null/empty bytes or was not configured.");
            }

            String successMsg = "Form submitted successfully!";
            if (damPdfPath != null) {
                successMsg += " DoR PDF saved to DAM at: " + damPdfPath;
            }

            setResponseStatus(result, true, successMsg);

        } catch (Exception e) {
            LOG.error("Error processing custom submit action with DoR generation", e);
            setResponseStatus(result, false, e.getMessage());
        }

        return result;
    }

    /**
     * Reads dorType and dorTemplateRef from the form container resource properties.
     * Returns the XDP template path only if dorType = "select" and dorTemplateRef is configured.
     */
    private String getDorTemplatePath(Resource containerResource) {
        ValueMap properties = containerResource.getValueMap();

        String dorType = properties.get(DOR_TYPE_PROPERTY, String.class);
        String dorTemplateRef = properties.get(DOR_TEMPLATE_REF_PROPERTY, String.class);

        LOG.info("Form Properties -> dorType: {}, dorTemplateRef: {}", dorType, dorTemplateRef);

        if (DOR_TYPE_SELECT.equals(dorType) && StringUtils.isNotBlank(dorTemplateRef)) {
            return dorTemplateRef;
        }

        return null;
    }

    private byte[] generateDoRPdfFromXdp(ResourceResolver resolver, String formData, String xdpTemplatePath) {
        Resource xdpResource = resolver.getResource(xdpTemplatePath);
        if (xdpResource == null) {
            LOG.error("XDP Template file not found at path: {}", xdpTemplatePath);
            return null;
        }

        try {
            InputStream xdpStream = getXdpInputStream(xdpResource);
            if (xdpStream == null) {
                LOG.error("Could not read InputStream for XDP template at path: {}", xdpTemplatePath);
                return null;
            }

            String xmlData = convertJsonToXmlData(formData);
            InputStream dataStream = new ByteArrayInputStream(xmlData.getBytes(StandardCharsets.UTF_8));

            Document xdpDoc = new Document(xdpStream);
            Document dataDoc = new Document(dataStream);

            PDFOutputOptions pdfOptions = new PDFOutputOptions();
            pdfOptions.setAcrobatVersion(AcrobatVersion.Acrobat_11);
            pdfOptions.setLinearizedPDF(true);

            Document pdfDocument = outputService.generatePDFOutput(xdpDoc, dataDoc, pdfOptions);
            if (pdfDocument != null) {
                return pdfDocument.getInlineData();
            }
        } catch (Exception e) {
            LOG.error("Failed to generate PDF from XDP template at path: {}", xdpTemplatePath, e);
        }
        return null;
    }

    /**
     * Converts JSON form payload into valid XFA Data XML matching Adobe Designer hierarchy structure
     * (form1 -> Subform1 -> fields) using Jackson ObjectMapper.
     */
    private String convertJsonToXmlData(String formData) {
        if (formData == null || !formData.trim().startsWith("{")) {
            return formData;
        }

        try {
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode rootNode = objectMapper.readTree(formData);

            StringBuilder xml = new StringBuilder();
            xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            xml.append("<form1><Subform1>");

            Iterator<Map.Entry<String, JsonNode>> fields = rootNode.fields();
            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> entry = fields.next();
                String key = entry.getKey();
                JsonNode value = entry.getValue();
                String valStr = value.isValueNode() ? value.asText() : value.toString();

                xml.append("<").append(key).append(">").append(escapeXml(valStr)).append("</").append(key).append(">");
                if (!key.startsWith("emp_")) {
                    xml.append("<emp_").append(key).append(">").append(escapeXml(valStr)).append("</emp_").append(key).append(">");
                }
            }

            xml.append("</Subform1></form1>");
            return xml.toString();

        } catch (Exception e) {
            LOG.warn("Could not parse JSON to XML using Jackson ObjectMapper: {}", e.getMessage());
            return formData;
        }
    }

    private String escapeXml(String str) {
        if (str == null) return "";
        return str.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;")
                  .replace("\"", "&quot;")
                  .replace("'", "&apos;");
    }

    private InputStream getXdpInputStream(Resource xdpResource) {
        if (xdpResource == null) return null;
        Asset asset = xdpResource.adaptTo(Asset.class);
        if (asset != null && asset.getOriginal() != null) {
            return asset.getOriginal().getStream();
        }
        return xdpResource.adaptTo(InputStream.class);
    }

    private String savePdfToDam(ResourceResolver resolver, byte[] pdfBytes) {
        if (resolver == null || pdfBytes == null || pdfBytes.length == 0) return null;

        try {
            AssetManager assetManager = resolver.adaptTo(AssetManager.class);
            if (assetManager == null) return null;

            Resource folderResource = resolver.getResource(DAM_DOR_FOLDER);
            if (folderResource == null) {
                ResourceUtil.getOrCreateResource(resolver, DAM_DOR_FOLDER, "sling:Folder", "sling:Folder", true);
            }

            String fileName = "DoR_" + System.currentTimeMillis() + "_" + UUID.randomUUID().toString().substring(0, 8) + ".pdf";
            String assetPath = DAM_DOR_FOLDER + "/" + fileName;

            Asset createdAsset = assetManager.createAsset(assetPath, new ByteArrayInputStream(pdfBytes), "application/pdf", true);
            if (createdAsset != null) {
                resolver.commit();
                LOG.info("Successfully stored DoR PDF to DAM at path: {}", assetPath);
                return assetPath;
            }
        } catch (Exception e) {
            LOG.error("Error saving generated DoR PDF to DAM", e);
        }
        return null;
    }

    private void setResponseStatus(Map<String, Object> result, boolean success, String message) {
        result.put("FormSubmissionComplete", success);
        result.put("guideSubmitStatus", success);
        result.put("submitStatus", success);
        result.put("status", success ? "success" : "error");

        if (success) {
            result.put("thankYouMessage", message);
            result.put("thankYouOption", "message");
        } else {
            result.put("guideSubmitError", message);
        }
    }
}